name: Proof Figma Tokens

# Evento que permite ejecutar el workflow manualmente
on:
  workflow_dispatch:

jobs:
  update-figma:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Llamar a la API de Figma para obtener las variables o tokens
    - name: Fetch Figma Variables
      run: |
        curl -H "X-FIGMA-TOKEN: ${{ secrets.FIGMA_API_TOKEN_TEMPORAL }}" \
        "https://api.figma.com/v1/files/<file_id>" \
        -o figma-design-tokens.json

    # 3. Configurar git para hacer commit y push de los cambios
    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add figma-design-tokens.json
        git commit -m "Updated Figma design tokens"
        git push
